// AUTO-GENERATED by scripts/inline-migrations.mjs — DO NOT EDIT BY HAND.
// Regenerate with `pnpm bundle` or `pnpm -F @glyphs-ai/schedule db:generate`.
// Source of truth: packages/schedule/drizzle/*.sql.
// biome-ignore-all format: keep generator output stable across runs.
// biome-ignore-all lint: generated, may include unused/long lines.

import type { Client } from "@libsql/client";
import type { MigrationMeta } from "drizzle-orm/migrator";

export const MIGRATIONS: readonly MigrationMeta[] = [
  {
    sql: [
      "CREATE TABLE `schedules` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`trigger_kind` text NOT NULL,\n\t`trigger_expr` text NOT NULL,\n\t`trigger_tz` text NOT NULL,\n\t`target_kind` text NOT NULL,\n\t`target_json` text NOT NULL,\n\t`target_agent` text,\n\t`enabled` integer DEFAULT true NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`last_fired_at` text,\n\t`next_fire_at` text\n);\n",
      "\nCREATE INDEX `schedules_enabled_idx` ON `schedules` (`enabled`);",
      "\nCREATE INDEX `schedules_next_fire_idx` ON `schedules` (`next_fire_at`);",
      "\nCREATE INDEX `schedules_target_agent_idx` ON `schedules` (`target_agent`);"
    ],
    bps: true,
    folderMillis: 1,
    hash: "847cb575719821100520be326745001dcca596ae9ae839422c4b821ea75658c1",
  },
  {
    sql: [
      "DROP INDEX `schedules_target_agent_idx`;\n",
      "\nALTER TABLE `schedules` DROP COLUMN `target_agent`;\n",
      "\nCREATE INDEX `schedules_target_agent_idx` ON `schedules` (json_extract(`target_json`, '$.agent')) WHERE `target_kind` = 'task';"
    ],
    bps: true,
    folderMillis: 2,
    hash: "19fe6665280e23e42ad0a6542b45bfe8b5c907882597f28d464f520efc4756bd",
  },
];

/**
 * Apply migrations against a libsql `client` using `batch(..., "write")`.
 *
 * **Per-pkg journal table**: `__drizzle_migrations_schedule`.
 */
export async function applyScheduleMigrations(client: Client): Promise<void> {
  await client.execute(
    "CREATE TABLE IF NOT EXISTS __drizzle_migrations_schedule (id INTEGER PRIMARY KEY, hash text NOT NULL, created_at numeric)",
  );
  const applied = await client.execute(
    "SELECT created_at FROM __drizzle_migrations_schedule ORDER BY created_at DESC LIMIT 1",
  );
  const lastRow = applied.rows.at(0);
  const lastMillis = lastRow !== undefined ? Number(lastRow.created_at) : -1;
  for (const migration of MIGRATIONS) {
    if (lastMillis >= migration.folderMillis) continue;
    await client.batch(
      [
        ...migration.sql,
        {
          sql: "INSERT INTO __drizzle_migrations_schedule (hash, created_at) VALUES (?, ?)",
          args: [migration.hash, migration.folderMillis],
        },
      ],
      "write",
    );
  }
}
