// AUTO-GENERATED by scripts/inline-migrations.mjs — DO NOT EDIT BY HAND.
// Regenerate with `pnpm bundle` or `pnpm -F @glyphs-ai/workflow db:generate`.
// Source of truth: packages/workflow/drizzle/*.sql.
// biome-ignore-all format: keep generator output stable across runs.
// biome-ignore-all lint: generated, may include unused/long lines.

import type { BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import type { MigrationMeta } from "drizzle-orm/migrator";

export const MIGRATIONS: readonly MigrationMeta[] = [
  {
    sql: [
      "CREATE TABLE `workflow_edges` (\n\t`workflow_id` text NOT NULL,\n\t`from_node_id` text NOT NULL,\n\t`to_node_id` text NOT NULL,\n\tPRIMARY KEY(`workflow_id`, `from_node_id`, `to_node_id`)\n);\n",
      "\nCREATE INDEX `workflow_edges_from_idx` ON `workflow_edges` (`workflow_id`,`from_node_id`);",
      "\nCREATE INDEX `workflow_edges_to_idx` ON `workflow_edges` (`workflow_id`,`to_node_id`);",
      "\nCREATE TABLE `workflow_nodes` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`workflow_id` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`spec_json` text NOT NULL,\n\t`phase` integer NOT NULL,\n\t`status` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`ready_at` text,\n\t`running_at` text,\n\t`ended_at` text\n);\n",
      "\nCREATE INDEX `workflow_nodes_workflow_idx` ON `workflow_nodes` (`workflow_id`);",
      "\nCREATE INDEX `workflow_nodes_status_idx` ON `workflow_nodes` (`workflow_id`,`status`);",
      "\nCREATE TABLE `workflows` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`brief` text NOT NULL,\n\t`cancellation` text,\n\t`coordinator_agent` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`details` text,\n\t`ended_at` text,\n\t`failure` text,\n\t`metadata` text DEFAULT '{}' NOT NULL,\n\t`started_at` text,\n\t`status` text NOT NULL,\n\t`success` text\n);\n",
      "\nCREATE INDEX `workflows_status_idx` ON `workflows` (`status`);",
      "\nCREATE INDEX `workflows_coordinator_agent_idx` ON `workflows` (`coordinator_agent`);"
    ],
    bps: true,
    folderMillis: 1,
    hash: "3ce054a4c9d068bbc43906a7390ff7a4a95966e954951b3fb6e1fe0352d89c95",
  },
  {
    sql: [
      "ALTER TABLE `workflow_nodes` ADD `metadata` text DEFAULT '{}' NOT NULL;"
    ],
    bps: true,
    folderMillis: 2,
    hash: "13000ce98cc3e4ca0edb012b7c26dc89a424d0bd4baeeff39e17b0fa0f6dfb2a",
  },
  {
    sql: [
      "ALTER TABLE `workflows` ADD `origin` text DEFAULT 'standalone' NOT NULL;",
      "\nCREATE INDEX `workflows_origin_idx` ON `workflows` (`origin`);"
    ],
    bps: true,
    folderMillis: 3,
    hash: "c3be965b5a18fd45a7511f77dc4179b9a91a8745730f0aac09ecb221391bfc86",
  },
  {
    sql: [
      "CREATE INDEX IF NOT EXISTS `workflows_schedule_id_idx`\n  ON `workflows` (json_extract(`metadata`, '$.scheduleId'))\n  WHERE `origin` = 'schedule';\n"
    ],
    bps: true,
    folderMillis: 4,
    hash: "18681abac79f1ed7164bd6caa36b4720aa1263671f3ecfcc19f4e72bc4dcb8d1",
  },
];

/**
 * Run drizzle's official migration applier against `db`. Thin typed
 * shim over drizzle's `@internal` `dialect` + `session` props (same
 * props drizzle's own `migrate()` from `drizzle-orm/better-sqlite3/migrator`
 * touches) so consumers don't repeat the cast.
 *
 * **Per-pkg `migrationsTable`**: `__drizzle_migrations_workflow`.
 * Each entity pkg owns its own journal table so co-tenant pkgs in the
 * same SQLite file don't trip drizzle's global `folderMillis` watermark
 * check — drizzle's own bookkeeping is namespaced by table, so per-pkg
 * tables let migrations apply independently. Every glyph pkg follows
 * the `__drizzle_migrations_<pkg>` convention; deviating from it would
 * silently re-apply migrations or skip them.
 */
export function applyWorkflowMigrations<T extends Record<string, unknown>>(
  db: BetterSQLite3Database<T>,
): void {
  const internals = db as unknown as {
    dialect: { migrate(m: readonly MigrationMeta[], s: unknown, c?: { migrationsTable: string }): void };
    session: unknown;
  };
  internals.dialect.migrate(MIGRATIONS, internals.session, {
    migrationsTable: "__drizzle_migrations_workflow",
  });
}
