// AUTO-GENERATED by scripts/inline-migrations.mjs — DO NOT EDIT BY HAND.
// Regenerate with `pnpm bundle` or `pnpm -F @glyphs-ai/schedule db:generate`.
// Source of truth: packages/schedule/drizzle/*.sql.
// biome-ignore-all format: keep generator output stable across runs.
// biome-ignore-all lint: generated, may include unused/long lines.

import type { BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import type { MigrationMeta } from "drizzle-orm/migrator";

export const MIGRATIONS: readonly MigrationMeta[] = [
  {
    sql: [
      "CREATE TABLE `schedules` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`trigger_kind` text NOT NULL,\n\t`trigger_expr` text NOT NULL,\n\t`trigger_tz` text NOT NULL,\n\t`target_kind` text NOT NULL,\n\t`target_json` text NOT NULL,\n\t`target_agent` text,\n\t`enabled` integer DEFAULT true NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`last_fired_at` text,\n\t`next_fire_at` text\n);\n",
      "\nCREATE INDEX `schedules_enabled_idx` ON `schedules` (`enabled`);",
      "\nCREATE INDEX `schedules_next_fire_idx` ON `schedules` (`next_fire_at`);",
      "\nCREATE INDEX `schedules_target_agent_idx` ON `schedules` (`target_agent`);"
    ],
    bps: true,
    folderMillis: 1,
    hash: "847cb575719821100520be326745001dcca596ae9ae839422c4b821ea75658c1",
  },
  {
    sql: [
      "DROP INDEX `schedules_target_agent_idx`;\n",
      "\nALTER TABLE `schedules` DROP COLUMN `target_agent`;\n",
      "\nCREATE INDEX `schedules_target_agent_idx` ON `schedules` (json_extract(`target_json`, '$.agent')) WHERE `target_kind` = 'task';"
    ],
    bps: true,
    folderMillis: 2,
    hash: "19fe6665280e23e42ad0a6542b45bfe8b5c907882597f28d464f520efc4756bd",
  },
];

/**
 * Run drizzle's official migration applier against `db`. Thin typed
 * shim over drizzle's `@internal` `dialect` + `session` props (same
 * props drizzle's own `migrate()` from `drizzle-orm/better-sqlite3/migrator`
 * touches) so consumers don't repeat the cast.
 *
 * **Per-pkg `migrationsTable`**: `__drizzle_migrations_schedule`.
 * Each entity pkg owns its own journal table so co-tenant pkgs in the
 * same SQLite file don't trip drizzle's global `folderMillis` watermark
 * check — drizzle's own bookkeeping is namespaced by table, so per-pkg
 * tables let migrations apply independently. Every glyph pkg follows
 * the `__drizzle_migrations_<pkg>` convention; deviating from it would
 * silently re-apply migrations or skip them.
 */
export function applyScheduleMigrations<T extends Record<string, unknown>>(
  db: BetterSQLite3Database<T>,
): void {
  const internals = db as unknown as {
    dialect: { migrate(m: readonly MigrationMeta[], s: unknown, c?: { migrationsTable: string }): void };
    session: unknown;
  };
  internals.dialect.migrate(MIGRATIONS, internals.session, {
    migrationsTable: "__drizzle_migrations_schedule",
  });
}
