// AUTO-GENERATED by scripts/inline-migrations.mjs — DO NOT EDIT BY HAND.
// Regenerate with `pnpm bundle` or `pnpm -F @glyphs-ai/workflow db:generate`.
// Source of truth: packages/workflow/drizzle/*.sql.
// biome-ignore-all format: keep generator output stable across runs.
// biome-ignore-all lint: generated, may include unused/long lines.

import type { Client } from "@libsql/client";
import type { MigrationMeta } from "drizzle-orm/migrator";

export const MIGRATIONS: readonly MigrationMeta[] = [
  {
    sql: [
      "CREATE TABLE `workflow_edges` (\n\t`workflow_id` text NOT NULL,\n\t`from_node_id` text NOT NULL,\n\t`to_node_id` text NOT NULL,\n\tPRIMARY KEY(`workflow_id`, `from_node_id`, `to_node_id`)\n);\n",
      "\nCREATE INDEX `workflow_edges_from_idx` ON `workflow_edges` (`workflow_id`,`from_node_id`);",
      "\nCREATE INDEX `workflow_edges_to_idx` ON `workflow_edges` (`workflow_id`,`to_node_id`);",
      "\nCREATE TABLE `workflow_nodes` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`workflow_id` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`spec_json` text NOT NULL,\n\t`phase` integer NOT NULL,\n\t`status` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`ready_at` text,\n\t`running_at` text,\n\t`ended_at` text\n);\n",
      "\nCREATE INDEX `workflow_nodes_workflow_idx` ON `workflow_nodes` (`workflow_id`);",
      "\nCREATE INDEX `workflow_nodes_status_idx` ON `workflow_nodes` (`workflow_id`,`status`);",
      "\nCREATE TABLE `workflows` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`brief` text NOT NULL,\n\t`cancellation` text,\n\t`coordinator_agent` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`details` text,\n\t`ended_at` text,\n\t`failure` text,\n\t`metadata` text DEFAULT '{}' NOT NULL,\n\t`started_at` text,\n\t`status` text NOT NULL,\n\t`success` text\n);\n",
      "\nCREATE INDEX `workflows_status_idx` ON `workflows` (`status`);",
      "\nCREATE INDEX `workflows_coordinator_agent_idx` ON `workflows` (`coordinator_agent`);"
    ],
    bps: true,
    folderMillis: 1,
    hash: "3ce054a4c9d068bbc43906a7390ff7a4a95966e954951b3fb6e1fe0352d89c95",
  },
  {
    sql: [
      "ALTER TABLE `workflow_nodes` ADD `metadata` text DEFAULT '{}' NOT NULL;"
    ],
    bps: true,
    folderMillis: 2,
    hash: "13000ce98cc3e4ca0edb012b7c26dc89a424d0bd4baeeff39e17b0fa0f6dfb2a",
  },
  {
    sql: [
      "ALTER TABLE `workflows` ADD `origin` text DEFAULT 'standalone' NOT NULL;",
      "\nCREATE INDEX `workflows_origin_idx` ON `workflows` (`origin`);"
    ],
    bps: true,
    folderMillis: 3,
    hash: "c3be965b5a18fd45a7511f77dc4179b9a91a8745730f0aac09ecb221391bfc86",
  },
  {
    sql: [
      "CREATE INDEX IF NOT EXISTS `workflows_schedule_id_idx`\n  ON `workflows` (json_extract(`metadata`, '$.scheduleId'))\n  WHERE `origin` = 'schedule';\n"
    ],
    bps: true,
    folderMillis: 4,
    hash: "18681abac79f1ed7164bd6caa36b4720aa1263671f3ecfcc19f4e72bc4dcb8d1",
  },
  {
    sql: [
      "ALTER TABLE `workflows` ADD COLUMN `origin_id` text;\n",
      "\nUPDATE `workflows` SET `origin_id` = json_extract(`metadata`, '$.scheduleId')\n  WHERE `origin` = 'schedule' AND json_extract(`metadata`, '$.scheduleId') IS NOT NULL;\n",
      "\nCREATE INDEX `workflows_origin_pair_idx` ON `workflows` (`origin`, `origin_id`) WHERE `origin_id` IS NOT NULL;\n",
      "\nCREATE TEMP TABLE `_assert_workflows_origin_backfill` (`x`);\n",
      "\nCREATE TEMP TRIGGER `_assert_workflows_origin_backfill_trg` BEFORE INSERT ON `_assert_workflows_origin_backfill`\nBEGIN\n  SELECT RAISE(FAIL, 'workflows backfill incomplete')\n  WHERE EXISTS (SELECT 1 FROM `workflows` WHERE `origin` != 'standalone' AND `origin_id` IS NULL);\nEND;\n",
      "\nINSERT INTO `_assert_workflows_origin_backfill` VALUES (1);\n",
      "\nDROP TRIGGER `_assert_workflows_origin_backfill_trg`;\n",
      "\nDROP TABLE `_assert_workflows_origin_backfill`;\n",
      "\nDROP INDEX IF EXISTS `workflows_schedule_id_idx`;\n"
    ],
    bps: true,
    folderMillis: 5,
    hash: "cb8b6a4b630981e32a6d8abfd0cc17e62ff3aa626f91d8887102710f5ae28a1c",
  },
];

/**
 * Apply migrations against a libsql `client` using `batch(..., "write")`.
 *
 * **Per-pkg journal table**: `__drizzle_migrations_workflow`.
 */
export async function applyWorkflowMigrations(client: Client): Promise<void> {
  await client.execute(
    "CREATE TABLE IF NOT EXISTS __drizzle_migrations_workflow (id INTEGER PRIMARY KEY, hash text NOT NULL, created_at numeric)",
  );
  const applied = await client.execute(
    "SELECT created_at FROM __drizzle_migrations_workflow ORDER BY created_at DESC LIMIT 1",
  );
  const lastRow = applied.rows.at(0);
  const lastMillis = lastRow !== undefined ? Number(lastRow.created_at) : -1;
  for (const migration of MIGRATIONS) {
    if (lastMillis >= migration.folderMillis) continue;
    await client.batch(
      [
        ...migration.sql,
        {
          sql: "INSERT INTO __drizzle_migrations_workflow (hash, created_at) VALUES (?, ?)",
          args: [migration.hash, migration.folderMillis],
        },
      ],
      "write",
    );
  }
}
