// AUTO-GENERATED by scripts/inline-migrations.mjs — DO NOT EDIT BY HAND.
// Regenerate with `pnpm bundle` or `pnpm -F @glyphs-ai/_template db:generate`.
// Source of truth: packages/_template/drizzle/*.sql.
// biome-ignore-all format: keep generator output stable across runs.
// biome-ignore-all lint: generated, may include unused/long lines.

import type { BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import type { MigrationMeta } from "drizzle-orm/migrator";

export const MIGRATIONS: readonly MigrationMeta[] = [
  {
    sql: [
      "CREATE TABLE `__entities__` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`archived` integer NOT NULL\n);\n"
    ],
    bps: true,
    folderMillis: 1,
    hash: "4dab6fa863158c5f50935922ff2c7f6bdd887b45cbd7326d3bce5ea7ac9b3bdc",
  },
];

/**
 * Run drizzle's official migration applier against `db`. Thin typed
 * shim over drizzle's `@internal` `dialect` + `session` props (same
 * props drizzle's own `migrate()` from `drizzle-orm/better-sqlite3/migrator`
 * touches) so consumers don't repeat the cast.
 *
 * **Per-pkg `migrationsTable`**: `__drizzle_migrations___PKG__`.
 * Each entity pkg owns its own journal table so co-tenant pkgs in the
 * same SQLite file don't trip drizzle's global `folderMillis` watermark
 * check — drizzle's own bookkeeping is namespaced by table, so per-pkg
 * tables let migrations apply independently. Every glyph pkg follows
 * the `__drizzle_migrations_<pkg>` convention; deviating from it would
 * silently re-apply migrations or skip them.
 */
export function apply__Entity__Migrations<T extends Record<string, unknown>>(
  db: BetterSQLite3Database<T>,
): void {
  const internals = db as unknown as {
    dialect: { migrate(m: readonly MigrationMeta[], s: unknown, c?: { migrationsTable: string }): void };
    session: unknown;
  };
  internals.dialect.migrate(MIGRATIONS, internals.session, {
    migrationsTable: "__drizzle_migrations___PKG__",
  });
}
