// AUTO-GENERATED by scripts/inline-migrations.mjs — DO NOT EDIT BY HAND.
// Regenerate with `pnpm bundle` or `pnpm -F @glyphs-ai/_template db:generate`.
// Source of truth: packages/_template/drizzle/*.sql.
// biome-ignore-all format: keep generator output stable across runs.
// biome-ignore-all lint: generated, may include unused/long lines.

import type { Client } from "@libsql/client";
import type { MigrationMeta } from "drizzle-orm/migrator";

export const MIGRATIONS: readonly MigrationMeta[] = [
  {
    sql: [
      "CREATE TABLE `__entities__` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`archived` integer NOT NULL\n);\n"
    ],
    bps: true,
    folderMillis: 1,
    hash: "4dab6fa863158c5f50935922ff2c7f6bdd887b45cbd7326d3bce5ea7ac9b3bdc",
  },
];

/**
 * Apply migrations against a libsql `client` using `batch(..., "write")`,
 * which runs each migration's statements atomically on the single client
 * connection.
 *
 * **Per-pkg journal table**: `__drizzle_migrations___PKG__`.
 * Each entity pkg owns its own table so co-tenant pkgs in one SQLite file
 * apply independently; the `created_at` watermark skips already-applied
 * migrations.
 */
export async function apply__Entity__Migrations(client: Client): Promise<void> {
  await client.execute(
    "CREATE TABLE IF NOT EXISTS __drizzle_migrations___PKG__ (id INTEGER PRIMARY KEY, hash text NOT NULL, created_at numeric)",
  );
  const applied = await client.execute(
    "SELECT created_at FROM __drizzle_migrations___PKG__ ORDER BY created_at DESC LIMIT 1",
  );
  const lastRow = applied.rows.at(0);
  const lastMillis = lastRow !== undefined ? Number(lastRow.created_at) : -1;
  for (const migration of MIGRATIONS) {
    if (lastMillis >= migration.folderMillis) continue;
    await client.batch(
      [
        ...migration.sql,
        {
          sql: "INSERT INTO __drizzle_migrations___PKG__ (hash, created_at) VALUES (?, ?)",
          args: [migration.hash, migration.folderMillis],
        },
      ],
      "write",
    );
  }
}
