// AUTO-GENERATED by scripts/inline-migrations.mjs — DO NOT EDIT BY HAND.
// Regenerate with `pnpm bundle` or `pnpm -F @glyphs-ai/task db:generate`.
// Source of truth: packages/task/drizzle/*.sql.
// biome-ignore-all format: keep generator output stable across runs.
// biome-ignore-all lint: generated, may include unused/long lines.

import type { BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import type { MigrationMeta } from "drizzle-orm/migrator";

export const MIGRATIONS: readonly MigrationMeta[] = [
  {
    sql: [
      "CREATE TABLE `tasks` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`agent` text NOT NULL,\n\t`runtime` text,\n\t`status` text NOT NULL,\n\t`brief` text NOT NULL,\n\t`details` text,\n\t`origin` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`started_at` text NOT NULL,\n\t`ended_at` text,\n\t`success` text,\n\t`failure` text,\n\t`cancellation` text,\n\t`metadata` text NOT NULL\n);\n",
      "\nCREATE INDEX `tasks_agent_idx` ON `tasks` (`agent`);",
      "\nCREATE INDEX `tasks_runtime_idx` ON `tasks` (`runtime`);",
      "\nCREATE INDEX `tasks_status_idx` ON `tasks` (`status`);",
      "\nCREATE INDEX `tasks_origin_idx` ON `tasks` (`origin`);"
    ],
    bps: true,
    folderMillis: 1,
    hash: "08f637650da2d5393e61a99e84b7fa83096ff2caf1abea0d7274eed09f2b06e6",
  },
  {
    sql: [
      "CREATE INDEX `tasks_schedule_id_idx`\n  ON `tasks` (json_extract(`metadata`, '$.scheduleId'))\n  WHERE `origin` = 'schedule';\n"
    ],
    bps: true,
    folderMillis: 2,
    hash: "78071717c7b3a3a8a17342a8b446c75c3642d3da441b323fecd726ae7bcb09e4",
  },
];

/**
 * Run drizzle's official migration applier against `db`. Thin typed
 * shim over drizzle's `@internal` `dialect` + `session` props (same
 * props drizzle's own `migrate()` from `drizzle-orm/better-sqlite3/migrator`
 * touches) so consumers don't repeat the cast.
 *
 * **Per-pkg `migrationsTable`**: `__drizzle_migrations_task`.
 * Each entity pkg owns its own journal table so co-tenant pkgs in the
 * same SQLite file don't trip drizzle's global `folderMillis` watermark
 * check — drizzle's own bookkeeping is namespaced by table, so per-pkg
 * tables let migrations apply independently. Every glyph pkg follows
 * the `__drizzle_migrations_<pkg>` convention; deviating from it would
 * silently re-apply migrations or skip them.
 */
export function applyTaskMigrations<T extends Record<string, unknown>>(
  db: BetterSQLite3Database<T>,
): void {
  const internals = db as unknown as {
    dialect: { migrate(m: readonly MigrationMeta[], s: unknown, c?: { migrationsTable: string }): void };
    session: unknown;
  };
  internals.dialect.migrate(MIGRATIONS, internals.session, {
    migrationsTable: "__drizzle_migrations_task",
  });
}
