// AUTO-GENERATED by scripts/inline-migrations.mjs — DO NOT EDIT BY HAND.
// Regenerate with `pnpm bundle` or `pnpm -F @glyphs-ai/session db:generate`.
// Source of truth: packages/session/drizzle/*.sql.
// biome-ignore-all format: keep generator output stable across runs.
// biome-ignore-all lint: generated, may include unused/long lines.

import type { Client } from "@libsql/client";
import type { MigrationMeta } from "drizzle-orm/migrator";

export const MIGRATIONS: readonly MigrationMeta[] = [
  {
    sql: [
      "CREATE TABLE `sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`agent` text NOT NULL,\n\t`runtime` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`runtime_session_id` text,\n\t`last_launch_mode` text\n);\n",
      "\nCREATE INDEX `sessions_agent_idx` ON `sessions` (`agent`);"
    ],
    bps: true,
    folderMillis: 1,
    hash: "4b69488b9a3064878750710568fd0e57f25f2898a89df0e3d1b83bbf06c8f1f7",
  },
];

/**
 * Apply migrations against a libsql `client` using `batch(..., "write")`,
 * which runs each migration's statements atomically on the *single* client
 * connection. This is deliberately NOT drizzle's `migrate()` (from
 * `drizzle-orm/libsql/migrator`): that opens a separate interactive-transaction
 * connection, which a plain `:memory:` url cannot share (every libsql
 * connection is its own in-memory db) — so drizzle's migrator can only run
 * against a file. Batch keeps a single connection, so the same applier works
 * for both file and `:memory:` (tests), with no leaked transaction handle.
 *
 * **Per-pkg journal table**: `__drizzle_migrations_session`. Each
 * entity pkg owns its own table so co-tenant pkgs in one SQLite file apply
 * independently; the `created_at` watermark skips already-applied
 * migrations.
 */
export async function applySessionMigrations(client: Client): Promise<void> {
  await client.execute(
    "CREATE TABLE IF NOT EXISTS __drizzle_migrations_session (id INTEGER PRIMARY KEY, hash text NOT NULL, created_at numeric)",
  );
  const applied = await client.execute(
    "SELECT created_at FROM __drizzle_migrations_session ORDER BY created_at DESC LIMIT 1",
  );
  const lastRow = applied.rows.at(0);
  const lastMillis = lastRow !== undefined ? Number(lastRow.created_at) : -1;
  for (const migration of MIGRATIONS) {
    if (lastMillis >= migration.folderMillis) continue;
    await client.batch(
      [
        ...migration.sql,
        {
          sql: "INSERT INTO __drizzle_migrations_session (hash, created_at) VALUES (?, ?)",
          args: [migration.hash, migration.folderMillis],
        },
      ],
      "write",
    );
  }
}
