// AUTO-GENERATED by scripts/inline-migrations.mjs — DO NOT EDIT BY HAND.
// Regenerate with `pnpm bundle` or `pnpm -F @glyphs-ai/session db:generate`.
// Source of truth: packages/session/drizzle/*.sql.
// biome-ignore-all format: keep generator output stable across runs.
// biome-ignore-all lint: generated, may include unused/long lines.

import type { BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import type { MigrationMeta } from "drizzle-orm/migrator";

export const MIGRATIONS: readonly MigrationMeta[] = [
  {
    sql: [
      "CREATE TABLE `sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`agent` text NOT NULL,\n\t`runtime` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`runtime_session_id` text,\n\t`last_launch_mode` text\n);\n",
      "\nCREATE INDEX `sessions_agent_idx` ON `sessions` (`agent`);"
    ],
    bps: true,
    folderMillis: 1,
    hash: "4b69488b9a3064878750710568fd0e57f25f2898a89df0e3d1b83bbf06c8f1f7",
  },
];

/**
 * Run drizzle's official migration applier against `db`. Thin typed
 * shim over drizzle's `@internal` `dialect` + `session` props (same
 * props drizzle's own `migrate()` from `drizzle-orm/better-sqlite3/migrator`
 * touches) so consumers don't repeat the cast.
 *
 * **Per-pkg `migrationsTable`**: `__drizzle_migrations_session`.
 * Each entity pkg owns its own journal table so co-tenant pkgs in the
 * same SQLite file don't trip drizzle's global `folderMillis` watermark
 * check — drizzle's own bookkeeping is namespaced by table, so per-pkg
 * tables let migrations apply independently. Every glyph pkg follows
 * the `__drizzle_migrations_<pkg>` convention; deviating from it would
 * silently re-apply migrations or skip them.
 */
export function applySessionMigrations<T extends Record<string, unknown>>(
  db: BetterSQLite3Database<T>,
): void {
  const internals = db as unknown as {
    dialect: { migrate(m: readonly MigrationMeta[], s: unknown, c?: { migrationsTable: string }): void };
    session: unknown;
  };
  internals.dialect.migrate(MIGRATIONS, internals.session, {
    migrationsTable: "__drizzle_migrations_session",
  });
}
