// AUTO-GENERATED by scripts/inline-migrations.mjs — DO NOT EDIT BY HAND.
// Regenerate with `pnpm bundle` or `pnpm -F @glyphs-ai/task db:generate`.
// Source of truth: packages/task/drizzle/*.sql.
// biome-ignore-all format: keep generator output stable across runs.
// biome-ignore-all lint: generated, may include unused/long lines.

import type { Client } from "@libsql/client";
import type { MigrationMeta } from "drizzle-orm/migrator";

export const MIGRATIONS: readonly MigrationMeta[] = [
  {
    sql: [
      "CREATE TABLE `tasks` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`agent` text NOT NULL,\n\t`runtime` text,\n\t`status` text NOT NULL,\n\t`brief` text NOT NULL,\n\t`details` text,\n\t`origin` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`started_at` text NOT NULL,\n\t`ended_at` text,\n\t`success` text,\n\t`failure` text,\n\t`cancellation` text,\n\t`metadata` text NOT NULL\n);\n",
      "\nCREATE INDEX `tasks_agent_idx` ON `tasks` (`agent`);",
      "\nCREATE INDEX `tasks_runtime_idx` ON `tasks` (`runtime`);",
      "\nCREATE INDEX `tasks_status_idx` ON `tasks` (`status`);",
      "\nCREATE INDEX `tasks_origin_idx` ON `tasks` (`origin`);"
    ],
    bps: true,
    folderMillis: 1,
    hash: "08f637650da2d5393e61a99e84b7fa83096ff2caf1abea0d7274eed09f2b06e6",
  },
  {
    sql: [
      "CREATE INDEX `tasks_schedule_id_idx`\n  ON `tasks` (json_extract(`metadata`, '$.scheduleId'))\n  WHERE `origin` = 'schedule';\n"
    ],
    bps: true,
    folderMillis: 2,
    hash: "78071717c7b3a3a8a17342a8b446c75c3642d3da441b323fecd726ae7bcb09e4",
  },
  {
    sql: [
      "ALTER TABLE `tasks` ADD COLUMN `origin_id` text;\n",
      "\nUPDATE `tasks` SET `origin_id` = json_extract(`metadata`, '$.scheduleId')\n  WHERE `origin` = 'schedule' AND json_extract(`metadata`, '$.scheduleId') IS NOT NULL;\n",
      "\nUPDATE `tasks` SET `origin_id` = json_extract(`metadata`, '$.workflowNodeId')\n  WHERE `origin` = 'workflow' AND json_extract(`metadata`, '$.workflowNodeId') IS NOT NULL;\n",
      "\nCREATE INDEX `tasks_origin_pair_idx` ON `tasks` (`origin`, `origin_id`) WHERE `origin_id` IS NOT NULL;\n",
      "\nCREATE TEMP TABLE `_assert_tasks_origin_backfill` (`x`);\n",
      "\nCREATE TEMP TRIGGER `_assert_tasks_origin_backfill_trg` BEFORE INSERT ON `_assert_tasks_origin_backfill`\nBEGIN\n  SELECT RAISE(FAIL, 'tasks backfill incomplete')\n  WHERE EXISTS (SELECT 1 FROM `tasks` WHERE `origin` NOT IN ('standalone') AND `origin_id` IS NULL);\nEND;\n",
      "\nINSERT INTO `_assert_tasks_origin_backfill` VALUES (1);\n",
      "\nDROP TRIGGER `_assert_tasks_origin_backfill_trg`;\n",
      "\nDROP TABLE `_assert_tasks_origin_backfill`;\n",
      "\nDROP INDEX IF EXISTS `tasks_schedule_id_idx`;\n"
    ],
    bps: true,
    folderMillis: 3,
    hash: "994e7649884854299a619d9e3d7d38e9831940fed69b48f08b6201d37847c006",
  },
];

/**
 * Apply migrations against a libsql `client` using `batch(..., "write")`,
 * which runs each migration's statements atomically on the *single* client
 * connection. This is deliberately NOT drizzle's `migrate()` (from
 * `drizzle-orm/libsql/migrator`): that opens a separate interactive-transaction
 * connection, which a plain `:memory:` url cannot share (every libsql
 * connection is its own in-memory db) — so drizzle's migrator can only run
 * against a file. Batch keeps a single connection, so the same applier works
 * for both file and `:memory:` (tests), with no leaked transaction handle.
 *
 * **Per-pkg journal table**: `__drizzle_migrations_task`. Each
 * entity pkg owns its own table so co-tenant pkgs in one SQLite file apply
 * independently; the `created_at` watermark skips already-applied
 * migrations.
 *
 * This package's journal table is `__drizzle_migrations_task`; its
 * migrations share one lineage with the `tasks` schema in a shared
 * workspace.db.
 */
export async function applyTaskMigrations(client: Client): Promise<void> {
  await client.execute(
    "CREATE TABLE IF NOT EXISTS __drizzle_migrations_task (id INTEGER PRIMARY KEY, hash text NOT NULL, created_at numeric)",
  );
  const applied = await client.execute(
    "SELECT created_at FROM __drizzle_migrations_task ORDER BY created_at DESC LIMIT 1",
  );
  const lastRow = applied.rows.at(0);
  const lastMillis = lastRow !== undefined ? Number(lastRow.created_at) : -1;
  for (const migration of MIGRATIONS) {
    if (lastMillis >= migration.folderMillis) continue;
    await client.batch(
      [
        ...migration.sql,
        {
          sql: "INSERT INTO __drizzle_migrations_task (hash, created_at) VALUES (?, ?)",
          args: [migration.hash, migration.folderMillis],
        },
      ],
      "write",
    );
  }
}
