// AUTO-GENERATED by scripts/inline-migrations.mjs — DO NOT EDIT BY HAND.
// Regenerate with `pnpm bundle` or `pnpm -F @glyphs-ai/catalog db:generate`.
// Source of truth: packages/catalog/drizzle/*.sql.
// biome-ignore-all format: keep generator output stable across runs.
// biome-ignore-all lint: generated, may include unused/long lines.

import type { Client } from "@libsql/client";
import type { MigrationMeta } from "drizzle-orm/migrator";

export const MIGRATIONS: readonly MigrationMeta[] = [
  {
    sql: [
      "CREATE TABLE `agent_files` (\n\t`row_id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`agent_fqn` text NOT NULL,\n\t`rel_path` text NOT NULL,\n\t`content` blob NOT NULL\n);\n",
      "\nCREATE INDEX `agent_files_agent_fqn_idx` ON `agent_files` (`agent_fqn`);",
      "\nCREATE TABLE `agent_mcp_dependencies` (\n\t`row_id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`source_fqn` text NOT NULL,\n\t`target_fqn` text NOT NULL\n);\n",
      "\nCREATE INDEX `agent_mcp_deps_src_idx` ON `agent_mcp_dependencies` (`source_fqn`);",
      "\nCREATE INDEX `agent_mcp_deps_tgt_idx` ON `agent_mcp_dependencies` (`target_fqn`);",
      "\nCREATE UNIQUE INDEX `agent_mcp_deps_uniq` ON `agent_mcp_dependencies` (`source_fqn`,`target_fqn`);",
      "\nCREATE TABLE `agent_skill_dependencies` (\n\t`row_id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`source_fqn` text NOT NULL,\n\t`target_fqn` text NOT NULL\n);\n",
      "\nCREATE INDEX `agent_skill_deps_src_idx` ON `agent_skill_dependencies` (`source_fqn`);",
      "\nCREATE INDEX `agent_skill_deps_tgt_idx` ON `agent_skill_dependencies` (`target_fqn`);",
      "\nCREATE UNIQUE INDEX `agent_skill_deps_uniq` ON `agent_skill_dependencies` (`source_fqn`,`target_fqn`);",
      "\nCREATE TABLE `agents` (\n\t`fqn` text PRIMARY KEY NOT NULL,\n\t`origin` text NOT NULL,\n\t`description` text NOT NULL,\n\t`version` text NOT NULL,\n\t`prereqs` text,\n\t`prereqs_ack` integer DEFAULT 1 NOT NULL,\n\t`disabled_by_user` integer DEFAULT 0 NOT NULL,\n\t`installed_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);\n",
      "\nCREATE INDEX `agents_origin` ON `agents` (`origin`);",
      "\nCREATE INDEX `agents_updated_at` ON `agents` (`updated_at`);",
      "\nCREATE TABLE `mcps` (\n\t`fqn` text PRIMARY KEY NOT NULL,\n\t`origin` text NOT NULL,\n\t`spec` text NOT NULL,\n\t`installed_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);\n",
      "\nCREATE INDEX `mcps_origin` ON `mcps` (`origin`);",
      "\nCREATE INDEX `mcps_updated_at` ON `mcps` (`updated_at`);",
      "\nCREATE TABLE `skill_files` (\n\t`row_id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`skill_fqn` text NOT NULL,\n\t`rel_path` text NOT NULL,\n\t`content` blob NOT NULL\n);\n",
      "\nCREATE INDEX `skill_files_skill_fqn_idx` ON `skill_files` (`skill_fqn`);",
      "\nCREATE TABLE `skill_mcp_dependencies` (\n\t`row_id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`source_fqn` text NOT NULL,\n\t`target_fqn` text NOT NULL\n);\n",
      "\nCREATE INDEX `skill_mcp_deps_src_idx` ON `skill_mcp_dependencies` (`source_fqn`);",
      "\nCREATE INDEX `skill_mcp_deps_tgt_idx` ON `skill_mcp_dependencies` (`target_fqn`);",
      "\nCREATE UNIQUE INDEX `skill_mcp_deps_uniq` ON `skill_mcp_dependencies` (`source_fqn`,`target_fqn`);",
      "\nCREATE TABLE `skill_skill_dependencies` (\n\t`row_id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`source_fqn` text NOT NULL,\n\t`target_fqn` text NOT NULL\n);\n",
      "\nCREATE INDEX `skill_skill_deps_src_idx` ON `skill_skill_dependencies` (`source_fqn`);",
      "\nCREATE INDEX `skill_skill_deps_tgt_idx` ON `skill_skill_dependencies` (`target_fqn`);",
      "\nCREATE UNIQUE INDEX `skill_skill_deps_uniq` ON `skill_skill_dependencies` (`source_fqn`,`target_fqn`);",
      "\nCREATE TABLE `skills` (\n\t`fqn` text PRIMARY KEY NOT NULL,\n\t`origin` text NOT NULL,\n\t`description` text NOT NULL,\n\t`version` text NOT NULL,\n\t`prereqs` text,\n\t`prereqs_ack` integer DEFAULT 1 NOT NULL,\n\t`installed_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);\n",
      "\nCREATE INDEX `skills_origin` ON `skills` (`origin`);",
      "\nCREATE INDEX `skills_updated_at` ON `skills` (`updated_at`);"
    ],
    bps: true,
    folderMillis: 1,
    hash: "8b095934ef0ddf94f15633fe54a6c12191b9517f132379126ec0d2e723713954",
  },
  {
    sql: [
      "CREATE TABLE `agent_agent_dependencies` (\n\t`row_id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`source_fqn` text NOT NULL,\n\t`target_fqn` text NOT NULL\n);\n",
      "\nCREATE INDEX `agent_agent_deps_src_idx` ON `agent_agent_dependencies` (`source_fqn`);",
      "\nCREATE INDEX `agent_agent_deps_tgt_idx` ON `agent_agent_dependencies` (`target_fqn`);",
      "\nCREATE UNIQUE INDEX `agent_agent_deps_uniq` ON `agent_agent_dependencies` (`source_fqn`,`target_fqn`);"
    ],
    bps: true,
    folderMillis: 2,
    hash: "0f274043ce82553c9016e8143fead137da6ff35eea5edafa1cb31df3d8428ef4",
  },
];

/**
 * Apply migrations against a libsql `client` using `batch(..., "write")`,
 * which runs each migration's statements atomically on the *single* client
 * connection. This is deliberately NOT drizzle's `migrate()` (from
 * `drizzle-orm/libsql/migrator`): that opens a separate interactive-transaction
 * connection, which a plain `:memory:` url cannot share (every libsql
 * connection is its own in-memory db) — so drizzle's migrator can only run
 * against a file. Batch keeps a single connection, so the same applier works
 * for both file and `:memory:` (tests), with no leaked transaction handle.
 *
 * **Per-pkg journal table**: `__drizzle_migrations_catalog`. Each
 * entity pkg owns its own table so co-tenant pkgs in one SQLite file apply
 * independently; the `created_at` watermark skips already-applied
 * migrations.
 */
export async function applyCatalogMigrations(client: Client): Promise<void> {
  await client.execute(
    "CREATE TABLE IF NOT EXISTS __drizzle_migrations_catalog (id INTEGER PRIMARY KEY, hash text NOT NULL, created_at numeric)",
  );
  const applied = await client.execute(
    "SELECT created_at FROM __drizzle_migrations_catalog ORDER BY created_at DESC LIMIT 1",
  );
  const lastRow = applied.rows.at(0);
  const lastMillis = lastRow !== undefined ? Number(lastRow.created_at) : -1;
  for (const migration of MIGRATIONS) {
    if (lastMillis >= migration.folderMillis) continue;
    await client.batch(
      [
        ...migration.sql,
        {
          sql: "INSERT INTO __drizzle_migrations_catalog (hash, created_at) VALUES (?, ?)",
          args: [migration.hash, migration.folderMillis],
        },
      ],
      "write",
    );
  }
}
